version: '3.3'

services:
  build-prod:
    container_name: build-prod
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    networks:
      - reactjs

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - build-prod
    networks:
      - reactjs

networks:
  reactjs:
