version: '3.8'

services:
  build-dev:
    container_name: build-dev
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/app/src
    networks:
      - reactjs

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - build-dev
    networks:
      - reactjs

networks:
  reactjs:
